services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    container_name: final_project_frontend

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_final_project
    ports:
      - "11434:11434"
    command: serve
    volumes:
      - ollama_data:/root/.ollama
    
  nginx:
    image: nginx:alpine
    container_name: nginx_finalProject
    ports: 
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
     - frontend
  postgres:
    image: postgres:16
    environment:
     - POSTGRES_USER=dev 
     - POSTGRES_PASSWORD=dev 
     - POSTGRES_DB=final_project 
    volumes:
     - ./config:/docker-entrypoint-initdb.d
    ports:
     - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
     - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres 
    environment:
      - DATABASE_URL=postgres://dev:dev@postgres:5432/final_project?sslmode=disable
volumes:
  ollama_data:
