services:
  frontend:
    build:
      context: finalProject
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    command: serve
    
  nginx:
    image: nginx:alpine
    container_name: server_nginx
    ports: 
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
     - frontend
